export const APP_MESSAGE = 'APP_MESSAGE';
export const APP_REMOVED = 'APP_REMOVED';
export const APP_RESET = 'APP_RESET';

export const DEBUG_MESSAGE = 'DEBUG_MESSAGE';
export const DEBUG_TOGGLE_PAUSE   = 'DEBUG_TOGGLE_PAUSE';

export const FETCHED_APPSTORE_LIST = 'FETCHED_APPSTORE_LIST';
export const FETCHING_APPSTORE_LIST = 'FETCHING_APPSTORE_LIST';
export const SELECT_APP_TO_INSTALL = 'SELECT_APP_TO_INSTALL';
export const TOGGLE_APP_RESOURCE =  'TOGGLE_APP_RESOURCE';

export const NETWORK_ACCESS = 'NETWORK_ACCESS';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const NETWORK_SUCCESS = 'NETWORK_SUCCESS';
export const NETWORK_COMPLETE = 'NETWORK_COMPLETE';

export const WINDOW_RESIZED = 'WINDOW_RESIZED';